### ISSUE TITLE
查询提示Please login

### ISSUE THREAD

**Issue by YouKnowMyEggs** [majesty17/cs_ys_helper#1]

**Comment by YouKnowMyEggs** [comment]
Sorry，没注意到配置里有Cookie，但实际查询显示效果是看不到角色命座。

**Comment by majesty17** [comment]
> Sorry，没注意到配置里有Cookie，但实际查询显示效果是看不到角色命座。

点左侧角色列表，右边有显示，打钩的就是已有命座

**Comment by YouKnowMyEggs** [comment]
> > Sorry，没注意到配置里有Cookie，但实际查询显示效果是看不到角色命座。
> 
> 点左侧角色列表，右边有显示，打钩的就是已有命座

![Snipaste_2020-12-29_11-07-46](https://user-images.githubusercontent.com/18475010/103255981-6ca46f00-49c6-11eb-9fd1-39f6dc234b82.png)
是不是可能是我编译环境的问题。

**Comment by majesty17** [comment]
> > > Sorry，没注意到配置里有Cookie，但实际查询显示效果是看不到角色命座。
> > 
> > 
> > 点左侧角色列表，右边有显示，打钩的就是已有命座
> 
> ![Snipaste_2020-12-29_11-07-46](https://user-images.githubusercontent.com/18475010/103255981-6ca46f00-49c6-11eb-9fd1-39f6dc234b82.png)
> 是不是可能是我编译环境的问题。

啊 我知道了，Utils.getRoleDetails 这个方法没找到cookie。。。

**Comment by YouKnowMyEggs** [comment]
> > > > Sorry，没注意到配置里有Cookie，但实际查询显示效果是看不到角色命座。
> > > 
> > > 
> > > 点左侧角色列表，右边有显示，打钩的就是已有命座
> > 
> > 
> > ![Snipaste_2020-12-29_11-07-46](https://user-images.githubusercontent.com/18475010/103255981-6ca46f00-49c6-11eb-9fd1-39f6dc234b82.png)
> > 是不是可能是我编译环境的问题。
> 
> 啊 我知道了，Utils.getRoleDetails 这个方法没找到cookie。。。

能正常查询到了，如果可以自动保存记录上次运行的COOKIE或者能从本地读取COOKIE应该会更方面一些。

**Comment by majesty17** [comment]
> 能正常查询到了，如果可以自动保存记录上次运行的COOKIE或者能从本地读取COOKIE应该会更方面一些。

可以在本地保存cookie拉~
